steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=Dockerfile
  - --build-arg=BASE_IMAGE=nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04
  - --build-arg=USE_CUDA_VERSION=cu117
  - --build-arg=PYTHON_VERSION=3.10
  - --build-arg=BUILD_NIGHTLY=false
  - --destination=us-central1-docker.pkg.dev/sereact/pickgpt-cr/sereact_ml_serve:0.0.4
  - --cache=true  # Enable caching
  - --cache-ttl=168h  # Set cache time-to-live (optional)
  - --context=.  # Specify the build context
  - --target=production-image
  - --compressed-caching=false
  - --cache-copy-layers=true
  env:
  - 'DOCKER_BUILDKIT=1'
# images:
# - 'us-central1-docker.pkg.dev/sereact/pickgpt-cr/sereact_ml_serve:0.0.4'
options:
  machineType: 'E2_HIGHCPU_32'
